### ISSUE TITLE
Unable to execute script at line 171. Expected: {

### ISSUE THREAD

**Issue by KarlPan** [Duduf-dev/Duik#181]
Unable to execute script at line 171. Expected: {

**Comment by Nico-Duduf** [comment]
see
http://www.duduf.com/forum/viewtopic.php?f=45&t=9721
and
http://www.duduf.com/forum/viewtopic.php?f=45&t=9709

Possibly encoding error from jsx

**Comment by Nico-Duduf** [comment]
changed files encoding to UTF-8 without BOM, this should fix this issue. Still need testing thoug
