### ISSUE TITLE
Difference between "Simplified-Chinese" and "Traditional-Chinese"

### ISSUE THREAD

**Issue by eZioPan** [Duduf-dev/Duik#198]
Hi,
there is a little suggestion for Chinese translation.
Generally, Chinese has two different character sets: Simplified-Chinese and Traditional-Chinese. My translation is based on Simplified one, and Traditional one may have different version(different character, even different grammar).

So, could "Dutranslator.languages.push(['zh','简体中文']);" become "Dutranslator.languages.push(['zh_HANS','简体中文']);"
And leave "Dutranslator.languages.push(['zh_HANT','繁體中文']);" for Traditional-Chinese?
Thanks!

**Comment by Nico-Duduf** [comment]
done
