### ISSUE TITLE
Auto Rig bug

### ISSUE THREAD

**Issue by ramu50** [Duduf-dev/Duik#80]
I created an Auto Rig for a bird, but the Right leg foot's rig doesn't work. See the following links for details: https://drive.google.com/file/d/0B68wJyAzqFBlMVhZbEZoekMxR0U/view?usp=sharing

**Comment by ramu50** [comment]
Sorry about the private link hassle, i have made it public on the web.

**Comment by Nico-Duduf** [comment]
Well, everything works as it should with Duik, what's weird is how you tried to rig the legs.

If you need the layers to bend, you'll have to add THREE puppet pins, thigh, calf, foot (here, you have only two)

If you just want to rotate the leg, the simplest way is to just place the anchor point of  the layer where you need, add a null object for the foot (needed by the autorig), and use the null you already created for the thigh, and voilà!
